config/routes.rb
ProjectADS::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources  :ads do
    post 'transfer_state', on: :member
    collection { get :search }
    resources :comments, :except => [:new, :show, :index]
    resources :images, only: :destroy
  end

  root :to => "ads#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "users/show", as: "user_root"

  namespace :admin do
    root :to => "static_pages#adminka"
    resources :types, :except => [:show]
    get "static_pages/adminka"
    get "ads/moderate"
    resources :users, :except => [:show, :new, :create]
  end
end

app/models/ad.rb
# == Schema Information
#
# Table name: ads
#
#  id         :integer          not null, primary key
#  content    :text
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  type_id    :integer
#  state      :string(255)
#  slug       :string(255)
#

require 'elasticsearch/model'

class Ad < ActiveRecord::Base

  extend FriendlyId
  friendly_id :slug_for_url, use: [:history, :slugged, :finders]

  def slug_for_url
    self.content[0..10]
  end

  def should_generate_new_friendly_id?
    slug.blank? || content_changed?
  end

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :user
  belongs_to :type
  has_many   :images, :dependent => :destroy
  has_many   :comments,  :dependent => :destroy, include: :user

  validates :content, :presence => true, length: { minimum: 2, maximum: 1000 }
  validates :type, :presence => true
  validates :user, :presence => true  

  attr_accessible :content, :type_id
  attr_protected  :state, :user_id

  accepts_nested_attributes_for :images, :reject_if => :all_blank,
                                :allow_destroy => true


  state_machine :initial => :draft do

    event :publish do
      transition :approved => :published
    end

    event :rejecte do
      transition :pending => :rejected
    end

    event :send_to_arch do
      transition :published => :archives
    end

    event :approve do
      transition :pending => :approved
    end

    event :send_to_pending do
      transition :draft => :pending
    end

    event :send_to_draft do
      transition [:published, :approved, :rejected, :pending, :archives] => :draft
    end
  end

  def time_out?
    self.updated_at <= Date.current - 3.days
  end

  def self.Published!
    Ad.find_all_by_state("approved").each do |ad|
      ad.publish
    end
  end

  def self.Archives!
    Ad.find_all_by_state("published").each do |ad|
      ad.send_to_arch if ad.time_out?
    end
  end

  def self.method_missing(meth, *args)
    proc = Proc.new { return where(:state => meth.to_s) }

    state_machine.states.each do |st|
      proc.call if meth.to_s == st.name.to_s
    end
    super
  end

  def self.respond_to_missing?(meth, include_private = false)
    state_machine.states.each do |st|
      return true if meth.to_s == st.name.to_s
    end
    super
  end
end

app/models/ads.rb
class Ads < ActiveRecord::Base
	belongs_to :user
  	validates :user_id, presence: true
end

app/controllers/admin/ads_controller.rb
class Admin::AdsController < ApplicationController
  include Admin::StaticPagesHelper

  before_filter :verify_admin

  def moderate
    @ads = Ad.paginate(:page => params[:page], :per_page => 5).
      pending.includes(:type, :user, :images)
    render "ads/index"
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  
  include AdsHelper

  load_and_authorize_resource

  skip_before_filter :authenticate_user! , :only => [:index]

  responders :flash, :http_cache

  def index
    @ads = Ad.paginate(:page => params[:page], :per_page => 5).
      published.includes(:type, :user, :images)
  end

  def show
    redirect_to @ad, status: :moved_permanently if request.path != ad_path(@ad)
    @comment = Comment.new
  end

  # GET /articles/search
  def search
    @ads = Ad.search(params[:q]).records.paginate(:page => params[:page], :per_page => 5).
      published.includes(:type, :user, :images)

    render action: "index"
  end

  def new
  end

  def create
    @ad.user = current_user
    @ad.images << upload_images_fro_url(params[:url_image])
    @ad.images.destroy_all unless @ad.save
    respond_with(@ad)
  end

  def edit
  end

  def update
    @ad.images << upload_images_fro_url(params[:url_image])
    @ad.update_attributes(params[:ad])
    respond_with(@ad)
  end

  def destroy
    @ad.destroy
    respond_with(@ad)
  end

  def transfer_state
    @ad.send(params[:transfer_method])
  end
end

app/helpers/ads_helper.rb
module AdsHelper
  require 'open-uri'
  def state_link(state_method, ads)
    if can?(state_method, ads) && ads.send("can_#{state_method}?")
      link_to(state_method.to_s + " | ",
        transfer_state_ad_path(transfer_method: state_method, 
        id: ads.id), method: :post, remote: true)
    end
  end

  def upload_images_fro_url(urls)
    images = Array.new
    urls.each do |url|
      begin
        images.push Image.new(photo: URI.parse(url)) unless url.blank?
      rescue
      end
    end
    images
  end
end

app/views/ads/_ad.html.slim
p
  b
    | User name:
  = ad.user.name
  br
  b
    | Type advertising:
  = ad.type.name
  br
  b
    | Status:
  = ad.state
  br
  br
  i
    == ad.content
  br
  = render_gallery_for ad.images, original: 'image_full', thumbnail: 'image_thumb'
  br
  br
  = link_to "Edit advertising | ", edit_ad_path(ad) if can? :edit, ad
  = link_to "Delete advertising", ad_path(ad), :method => :delete, :confirm => "Y/N?", :title => "Delete?" if can? :destroy, ad
  br
  - [:send_to_draft, :send_to_pending, :rejecte, :approve].each do |transfer_method|
    = state_link transfer_method, ad
  br
  = link_to "Read more...", ad_path(ad)
  br
  |  ----------------------------------------------- 
  br
  br

app/views/ads/_ad_form.html.slim
= simple_nested_form_for @ad do |f|
  = f.association :type
  = f.input :content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} }
  br
  | Add photos or images: 
  br
  br
  = f.fields_for :images, Image.new do |img_form|
    = img_form.file_field :photo
    p
      |  -------------- or -------------- 
    = label_tag 'Url:'
    = text_field_tag "url_image[]"
    br
    = img_form.link_to_remove 'Remove this photo'
    br
    br
  = f.link_to_add 'Add photo', :images
  br
  br
  = f.button :submit
- @ad.images.each do |img|
  p
    = img.photo.original_filename
    = link_to "delete", ad_image_path(@ad, img), :method => :delete, :confirm => "Y/N?", :title => "Delete?"
    br

app/views/ads/edit.html.slim
- provide(:title, 'Edit ad')
= render "ad_form"

app/views/ads/index.html.slim
- provide(:title, 'Show ADS')
- if params[:controller] == "ads"
  = form_tag("/ads/search", method: :get) do
    = label_tag :query
    = text_field_tag :q, params[:q]
    br
    = submit_tag :search, class: 'btn btn-primary'
= will_paginate @ads
= render partial: "ads/ad", collection: @ads
= will_paginate @ads

app/views/ads/new.html.slim
- provide(:title, 'New ad')
= render 'ad_form'

app/views/ads/show.html.slim
- provide(:title, 'Ads')
= render @ad
h2
  | Comments:
= sync partial: 'comment', collection: @ad.comments
= sync_new partial: 'comment', resource: Comment.new, scope: @ad
h2
  | Add a comment:
= render 'comments/comment_form'

app/views/ads/transfer_state.js.slim
| location.reload(); 