config/routes.rb
ProjectADS::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources  :ads do
    post 'transfer_state', on: :member
    collection { get :search }
    resources :comments, :except => [:new, :show, :index]
    resources :images, only: :destroy
  end

  root :to => "ads#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "users/show", as: "user_root"

  namespace :admin do
    root :to => "static_pages#adminka"
    resources :types, :except => [:show]
    get "static_pages/adminka"
    get "ads/moderate"
    resources :users, :except => [:show, :new, :create]
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  text       :string(255)
#  user_id    :integer
#  ad_id      :integer
#  created_at :datetime
#  updated_at :datetime
#  parent_id  :integer
#  lft        :integer
#  rgt        :integer
#

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :ad

  attr_accessible :text
  attr_protected :user_id, :ad_id
  
  validates :text, :presence => true, length: { minimum: 2, maximum: 1000 }
  validates :user, :presence => true
  validates :ad, :presence => true
  
  sync :all
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
  load_and_authorize_resource

  enable_sync only: [:create, :update, :destroy]

  def create
    @ad = Ad.find(params[:ad_id])
    @comment.ad = @ad
    @comment.user = current_user
    respond_with(@comment) do |format|
      if @comment.save
        UserMailer.notification_for_new_comment_for_ad(@ad, current_user).deliver
        sync_new @comment, scope: @ad
        format.html { redirect_to @ad }
      else
        format.html { render :action => "edit" }
      end 
    end
  end

  def edit
    @ad = Ad.find(params[:ad_id])
  end

  def update
    @ad = Ad.find(params[:ad_id])
    respond_with(@comment) do |format|
      if @comment.update_attributes(params[:comment])
        sync_update @comment
        format.html { redirect_to @ad }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    sync_destroy @comment if @comment.destroy
    respond_with(@comment) do |format|
      format.html { redirect_to ad_path(Ad.find(params[:ad_id])) }
    end
  end
end

app/views/comments/_comment.html.erb
  <p>  
    UserName:
    <%= comment.user.name %> <br />
    comment:
    <%= comment.text   %>
    <%= link_to "edit |", edit_ad_comment_path(@ad, comment) if can? :edit, comment %> 
    <%= link_to "delete", ad_comment_path(@ad, comment), :method => :delete, :confirm => "Y/N?", :title => "Delete?" if can? :destroy, comment  %> <br />
  </p>

app/views/comments/_comment_form.html.slim
= simple_form_for([@ad, @comment]) do |f|
  p
    = f.label :text
    br
    = f.text_area :text
  p
    = f.submit "Add comment", class: "btn btn-success"

app/views/comments/edit.html.slim
- provide(:title, 'Edit comment')
= render 'comment_form'