config/routes.rb
ProjectADS::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources  :ads do
    post 'transfer_state', on: :member
    collection { get :search }
    resources :comments, :except => [:new, :show, :index]
    resources :images, only: :destroy
  end

  root :to => "ads#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "users/show", as: "user_root"

  namespace :admin do
    root :to => "static_pages#adminka"
    resources :types, :except => [:show]
    get "static_pages/adminka"
    get "ads/moderate"
    resources :users, :except => [:show, :new, :create]
  end
end

app/controllers/admin/types_controller.rb
class Admin::TypesController < ApplicationController
  load_and_authorize_resource
  
  responders :flash, :http_cache

  def create
    @type = Type.new(name: params[:type][:name])
    respond_with(@type) do |format|
      if @type.save
        format.html { redirect_to(admin_types_path) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def destroy
    @type.destroy
    respond_with(@type) do |format|
      format.html { redirect_to(admin_types_path) }
    end
  end

  def update
    respond_with(@type) do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to(admin_types_path) }
      else
        format.html { render :action => "new" }
      end
    end
  end
end

app/views/admin/types/_form_type.html.slim
= simple_form_for [:admin, @type] do |f|
  = f.error_notification
  = f.input :name
  = f.button :submit

app/views/admin/types/edit.html.slim
- provide(:title, 'Edit type')
= render 'form_type'

app/views/admin/types/index.html.slim
- provide(:title, 'Types')
- @types.each do |type|
  / = type.id
  / |  : 
  = type.name
  = button_to 'edit', edit_admin_type_path(type), class: "btn btn-warning", method: :get
  = button_to 'delete', admin_type_path(type), :method => :delete, :confirm => "Y/N?", :title => "Delete type #{type.name}", class: "btn btn-danger"
= button_to 'Create new type', new_admin_type_path, class: "btn btn-success", method: :get
= button_to 'Back', :back, :method => :get, class: "btn btn-default btn-lg"

app/views/admin/types/new.html.slim
- provide(:title, 'New type')
= render 'form_type'