config/routes.rb
ProjectADS::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources  :ads do
    post 'transfer_state', on: :member
    collection { get :search }
    resources :comments, :except => [:new, :show, :index]
    resources :images, only: :destroy
  end

  root :to => "ads#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "users/show", as: "user_root"

  namespace :admin do
    root :to => "static_pages#adminka"
    resources :types, :except => [:show]
    get "static_pages/adminka"
    get "ads/moderate"
    resources :users, :except => [:show, :new, :create]
  end
end

app/views/layouts/_footer.html.slim
footer

app/views/layouts/_header.html.slim
header.navbar
  .navbar-inner
    = link_to 'Home', root_path, class: "brand"
    ul.nav
      - if user_signed_in?
        li.divider-vertical
          = link_to "Hi, #{current_user.email}", user_root_path
        li.divider-vertical
          = link_to 'Sign out', destroy_user_session_path, :method => :delete
        li.divider-vertical
          = link_to 'New', new_ad_path
        li.divider-vertical
          = link_to 'Adminka', admin_root_path if can? :set_role, User
        li.divider-vertical
          = link_to 'Edit my profile', edit_user_registration_path
      - else
        li.divider-vertical
          = link_to 'Sign in', new_user_session_path
        li.divider-vertical
          = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
        li.divider-vertical
          = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag Sync.adapter_javascript_url
    = csrf_meta_tags
  body
    = render 'layouts/header'
    p

    center
      = link_to image_tag("main_icon.jpg", alt: "ProjectADS"), root_path
    - flash.each do |key, value|
      div class="alert alert- #{key}"
        = value
    br
    br
    .container
      = yield
      = debug(params) if Rails.env.development?